### ISSUE TITLE
Issue Report in uriUriStringToUnixFilenameA

### ISSUE THREAD

**Issue by YancyLii** [uriparser/uriparser#205]
# Summary
A stack-buffer-overflow was detected in the uriUriStringToUnixFilenameA function. This issue occurs when the function writes more data to the provided buffer than its allocated size, leading to memory corruption and potential function problem.

# Steps to Reproduce:
1. Download the tar.gz file and decompress it, then (sudo) execute shell script
2. ./reproduce.sh
3. Observe the error message

[Test_uriparser_1.tar.gz](https://github.com/user-attachments/files/17810662/Test_uriparser_1.tar.gz)

**Comment by hartwork** [comment]
Hi @YancyLii,

sorry that I have not had time to look at your report via e-mail yet: work and other security work have kept me busy.

With regard to the report here, my impression is that:
- the fuzzing input does not contain any zero bytes
- the fuzzer creates input that lacks a nul terminator
- passes an non-terminated string to `uriParseUriA` (which is not supported use of the API)
- passes an non-terminated string to `uriUriStringToUnixFilenameA` (which is not supported use of the API)
- calls out to `uriComposeQueryExA` with a NULL `queryList` which makes it returns with benign `URI_ERROR_NULL` and not having any relation to the fuzzer input.

Once I fix two things —

1. append a nul byte to the fuzzing input
2. fix `char filename[2048]` to be `char filename[2086 + 1 + 1]` so that it respects the [documented input requirements](https://uriparser.github.io/doc/api/latest/Uri_8h.html#a4afbc8453c7013b9618259bc57d81a39) of uriUriStringToUnixFilenameA

…the fuzzer no longer crashes.

Therefore my conclusion is: works as expected, no security issues found here. We can discuss whether the API docs should mention their expectation about nul-terminated strings or if that goes without saying.

What do you think?

**Comment by YancyLii** [comment]
Yep, you're right.

**Comment by hartwork** [comment]
@YancyLii thanks for the confirmation! :+1: Closing now…
