### ISSUE TITLE
Memory leak in `uriParseUriA` function?

### ISSUE THREAD

**Issue by YancyLii** [uriparser/uriparser#208]
A memory leak is detected by LeakSanitizer in the uriParseUriA function during fuzz testing. The leak occurs due to allocated memory not being freed properly, resulting in an undetected leak of 32 bytes. This is triggered when the fuzz driver invokes URI parsing functions but does not clean up resources after usage.

Steps to Reproduce:
[Test_uriparser.tar.gz](https://github.com/user-attachments/files/18034133/Test_uriparser.tar.gz)
1. Download the tar.gz file and decompress it, then (sudo) execute shell script
2. ./Test_uriparser_1 leak-fb118762e37319833906f2dcb6932b57e377593f
3. Observe the error message

Bug analysis:
The memory leak is caused by improper memory management within the uriParseUriA function, which allocates memory via calloc but does not free it under certain failure conditions. Specifically:

The uriParseUriA function, which internally calls uriParseMustBeSegmentNzNcA, allocates memory but fails to release it when an error or failure occurs during URI parsing.
The allocated memory is not properly freed, resulting in a memory leak of 32 bytes, as reported by LeakSanitizer.
Additionally, the fuzz driver does not fully handle all possible error paths, which exacerbates the problem, as some resources (such as UriQueryListA) may not be initialized or cleaned up properly in certain cases.

**Comment by hartwork** [comment]
Hi @YancyLii,

I played with your report now and I found that:
- (`reproduce.sh` needs addition of `cd uriparser` after `git clone` to work out of the box (but that's a side note))
- (`char uri_string[2048];` is too short to hold a 2048 length string plus zero terminator (but that's a side note))
- The call to `uriFreeUriMembersA(&uri);` needs to be moved out (and below) the `uriToStringA` success guard — the third `if` body — so that it's running even when `uriToStringA` fails
- With that patch, LeakSanatizer stops complaining.

Based on that I'm concluding this report to be a false positive. What do you think?

**Comment by YancyLii** [comment]
I agree.

**Comment by hartwork** [comment]
Thank you!
